// Product Data
const products = [
    {
        id: 1,
        name: "Wireless Headphones",
        category: "electronics",
        price: 79.99,
        originalPrice: 129.99,
        discount: 38,
        description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
        icon: "fa-headphones",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
        rating: 4.5
    },
    {
        id: 2,
        name: "Smart Watch",
        category: "electronics",
        price: 199.99,
        originalPrice: 299.99,
        discount: 33,
        description: "Fitness tracking smart watch with heart rate monitor and GPS.",
        icon: "fa-watch",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
        rating: 4.8
    },
    {
        id: 3,
        name: "Laptop Stand",
        category: "electronics",
        price: 39.99,
        originalPrice: 59.99,
        discount: 33,
        description: "Ergonomic laptop stand with adjustable height and angle.",
        icon: "fa-laptop",
        image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&h=500&fit=crop",
        rating: 4.3
    },
    {
        id: 4,
        name: "Wireless Mouse",
        category: "electronics",
        price: 29.99,
        originalPrice: 49.99,
        discount: 40,
        description: "Ergonomic wireless mouse with precision tracking.",
        icon: "fa-computer-mouse",
        image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop",
        rating: 4.6
    },
    {
        id: 5,
        name: "Casual T-Shirt",
        category: "clothing",
        price: 24.99,
        originalPrice: 39.99,
        discount: 37,
        description: "100% cotton comfortable t-shirt available in multiple colors.",
        icon: "fa-shirt",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop",
        rating: 4.4
    },
    {
        id: 6,
        name: "Denim Jeans",
        category: "clothing",
        price: 59.99,
        originalPrice: 89.99,
        discount: 33,
        description: "Classic fit denim jeans with premium quality fabric.",
        icon: "fa-vest",
        image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&h=500&fit=crop",
        rating: 4.7
    },
    {
        id: 7,
        name: "Running Shoes",
        category: "clothing",
        price: 89.99,
        originalPrice: 139.99,
        discount: 36,
        description: "Lightweight running shoes with excellent cushioning and support.",
        icon: "fa-shoe-prints",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
        rating: 4.9
    },
    {
        id: 8,
        name: "Winter Jacket",
        category: "clothing",
        price: 129.99,
        originalPrice: 199.99,
        discount: 35,
        description: "Warm and stylish winter jacket with water-resistant coating.",
        icon: "fa-vest-patches",
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop",
        rating: 4.6
    },
    {
        id: 9,
        name: "JavaScript Guide",
        category: "books",
        price: 34.99,
        originalPrice: 49.99,
        discount: 30,
        description: "Comprehensive guide to modern JavaScript programming.",
        icon: "fa-book",
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop",
        rating: 4.7
    },
    {
        id: 10,
        name: "Python for Beginners",
        category: "books",
        price: 29.99,
        originalPrice: 44.99,
        discount: 33,
        description: "Learn Python programming from scratch with practical examples.",
        icon: "fa-book-open",
        image: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=500&h=500&fit=crop",
        rating: 4.8
    },
    {
        id: 11,
        name: "Web Design Masterclass",
        category: "books",
        price: 44.99,
        originalPrice: 69.99,
        discount: 36,
        description: "Master web design with HTML, CSS, and modern frameworks.",
        icon: "fa-book-bookmark",
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop",
        rating: 4.5
    },
    {
        id: 12,
        name: "Machine Learning Basics",
        category: "books",
        price: 54.99,
        originalPrice: 79.99,
        discount: 31,
        description: "Introduction to machine learning algorithms and applications.",
        icon: "fa-graduation-cap",
        image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=500&h=500&fit=crop",
        rating: 4.9
    },
    {
        id: 13,
        name: "Coffee Maker",
        category: "home",
        price: 79.99,
        originalPrice: 119.99,
        discount: 33,
        description: "Programmable coffee maker with thermal carafe and auto-brew feature.",
        icon: "fa-mug-hot",
        image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500&h=500&fit=crop",
        rating: 4.4
    },
    {
        id: 14,
        name: "Table Lamp",
        category: "home",
        price: 45.99,
        originalPrice: 69.99,
        discount: 34,
        description: "Modern LED table lamp with adjustable brightness and color temperature.",
        icon: "fa-lightbulb",
        image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&h=500&fit=crop",
        rating: 4.6
    },
    {
        id: 15,
        name: "Throw Pillow Set",
        category: "home",
        price: 34.99,
        originalPrice: 54.99,
        discount: 36,
        description: "Set of 4 decorative throw pillows with removable covers.",
        icon: "fa-couch",
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500&h=500&fit=crop",
        rating: 4.3
    },
    {
        id: 16,
        name: "Wall Clock",
        category: "home",
        price: 28.99,
        originalPrice: 44.99,
        discount: 36,
        description: "Silent wall clock with modern design and large numbers.",
        icon: "fa-clock",
        image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500&h=500&fit=crop",
        rating: 4.5
    }
];
